### PR TITLE
Fix kernel version when kernel is updated

### PR DESCRIPTION
**Pull request by lzala**
When performing full upgrade and a new kernel is available dkms is executed automatically. Unfortunattly the Makefile is not able to detect this. Introduce KVERSION=$kernelver in order to fix the issue.

https://linux.die.net/man/8/dkms
DKMS.CONF VARIABLES -> $kernelver

### CODE REVIEW

**Comment by lzala** [comment]
Please have a look on my finding and proposal

**Comment by gary0124** [comment]
sorry for review late and thanks for the commit, did you try all existing kernel can build with your modication?

**Comment by lzala** [comment]
It should not be an issue with the kernel versions if my understanding. This should be the standard approach to pass the kernel version when using DKMS

Better explained here: 
https://help.ubuntu.com/community/DKMS
 
Screenshot from 2023-04-27 10-37-19

**Comment by lzala** [comment]
I have tested the patch with 5.15.0-67-generic to 5.15.0-69-generic since this was available at the time and was failing because of the symbols table mismatch

**Pull request merged**
